var FuzzyMatching = require('fuzzy-matching');

var fm = new FuzzyMatching([
	'Testaussteller F&L 1',
	'honeyfaktur Paul Büki',
	'honeyfaktur',
	'Colourfood GmbH',
	'Colourfood',
	'Wolfra Bayrische Natursaft Kelterei GmbH',
	'Wolfra Kelterei',
	'allesOlive Feinkosthandel e.K.',
	'allesOlive',
	'Hennes’ Finest GmbH & Co. KG',
	'Hennes’ Finest',
	'Munich Brew Mafia',
	'Munich Brew',
	'Del Fiore GmbH',
	'Del Fiore',
	'Appenzeller Käse GmbH',
	'Appenzeller Käse',
	'E. Maria Gerhardt Wein & Sekt GmbH',
	'E. Maria Gerhardt',
	'Mr. Cheese Online Vertriebs GmbH',
	'Mr. Cheese',
	'Bliesgau Ölmühle GbR',
	'Bliesgau Ölmühle',
	'Marc & Kay GmbH',
	'c/o Teeblatt',
	'Marc & Kay',
	'IDM Südtirol - Alto Adige',
	'IDM Südtirol',
	'FrankenTourismus',
	'FrankenTourismus',
	'Soul of Wine Mühlbauer & Reich GbR',
	'Soul of Wine',
	'myChipsBox GmbH',
	'myChipsBox',
	'Vera Iannettova',
	'Specialitá di Parma',
	'Vera Iannettova',
	'Caffè Pol GmbH',
	'POL',
	'Whisky Shop - Feine Tropfen Online UG',
	'Whisky Shop',
	'Agrica Agrarhandels GmbH',
	'Agrica',
	'Schönegger Käse-Alm GmbH',
	'Schönegger',
	'ARGANVIV ARGANÖL',
	'Khalil Tangi',
	'ARGANVIV',
	'Patrick Lisbert',
	'Patrick Lisbert',
	'Naha Tea',
	'NAHA TEA',
	'Gutscheinbuch.de',
	'Gutscheinbuch.de',
	'Käsealm Marianne Moosbrugger',
	'Marianne Moosbrugger',
	'Käsealm',
	'Casa Vinya-Mallorca S.L.',
	'Casa Vinya',
	'Die Trüffelmanufaktur e.K.',
	'Trüffelmanufaktur',
	'Zum Entenwirt',
	'Peter Schrödl',
	'Zum Entenwirt',
	'Wein-Brasilien GmbH & Co KG',
	'Wein-Brasilien',
	'Cornelia Koch',
	'Träumen und Verwöhnen',
	'Cornelia Koch',
	'Christoph Gratl',
	'Weingut Gratl',
	'Christoph Gratl',
	'Weingut Hinter der Kirche',
	'Hinter der Kirche',
	'Montenauer Schinkenräucherei PGMBH',
	'Jambon D´ardenne Appellation D´Origine',
	'Montenauer Schinkenräucherei',
	'Wein- und Sektkellerei Lionel Dufour GmbH',
	'Lionel Dufour',
	'Piazza Culinaria',
	'Inh. Regina Lomberg',
	'Piazza Culinaria',
	'Weingut Fuchs-Jacobus',
	'Demeter Weingut',
	'Weingut Fuchs-Jacobus',
	'Weingut Schmidt-Kunz',
	'Weingut Schmidt-Kunz',
	'Kammermeier´s schärfste Saucen',
	'Rudolf Kammermeier',
	'Rudolf Kammermeier',
	'Johanna Harzig-Neira',
	'Import & Export',
	'Café SierrAzul',
	'Café SierrAzul',
	'Ökologisches Weingut Hubert Lay',
	'Hubert Lay',
	'Madavanilla - Vanille',
	'Christian Terno',
	'Madavanilla',
	'Weingut Jakob Christ',
	'Jakob Christ',
	'CMF-Produkte Keller',
	'Michael Keller',
	'Goufrais',
	'CMF-Produkte',
	'Weingut Fuchs',
	'Weingut Fuchs',
	'Winzermeister Jochen Funk',
	'Jochen Funk',
	'Galeria Eldorado',
	'Constanza Ordoñez de Meisel',
	'Galeria Eldorado',
	'Johann Schneeberger GmbH',
	'Weingut und Steirische Kellerei',
	'Johann Schneeberger',
	'Von Gaisbergsche Schlosskellerei GmbH',
	'Schlosskellerei',
	'Fischzucht Aumühle GbR',
	'Fischzucht Aumühle',
	'Deutsche Medien-Manufaktur GmbH & Co. KG',
	'Deutsche Medien-Manufaktur',
	'Selot & Sohn GmbH',
	'Selot & Sohn',
	'Herrmann Gewürze',
	'Inhaber: Norbert Herrmann',
	'Herrmann Gewürze',
	'Hofbäckerei Steingraber',
	'Hofbäckerei Steingraber',
	'Enzianbrennerei Grassl',
	'GmbH & Co. KG',
	'Enzianbrennerei Grassl',
	'Aktiv Naturheilmittel',
	'Wolfgang Stickling',
	'Aktiv Naturheilmittel',
	'Jules Muller & Fils GmbH',
	'Jules Muller & Fils',
	'Met-Amensis Honigwein Kellerei',
	'Met-Amensis',
	'Acetaia Montale Rangone Srl',
	'Acetaia Montale Rangone',
	'Schalk Mühle KG',
	'Getreide- und Ölmühle',
	'Schalk Mühle KG',
	'Boscariol Prodotti Tipici Italiani SNC',
	'Boscariol',
	'Weingut Sonenbuerg GbR',
	'Erwin Sauerwein',
	'Weingut Sonenbuerg',
	'Russo Angelo',
	'Salami und Käse aus Italien',
	'Russo Angelo',
	'Flötzinger Brauerei Franz Steegmüller GmbH & Co. KG',
	'Flötzinger Brauerei',
	'Anzenberger Kürbiskernöl',
	'Anzenberger Kürbiskernöl',
	'LA FATTORIA DI PRISCILLA',
	"SOCIETA' AGRICOLA A R.L.",
	'LA FATTORIA DI PRISCILLA',
	'Donato Volpe',
	'Villa Volpe',
	'Donato Volpe',
	'Gräfliche Brauerei',
	'Arco-Valley GmbH& Co KG',
	'Gräfliche Brauerei',
	'Markus Wieser GmbH - Deutschland',
	'Markus Wieser',
	'Schätzl GmbH',
	'Schätzl',
	'Nadia Mauro',
	'Nadia Mauro',
	'Château André Ziltener SA',
	'Château André Ziltener',
	'Bundesministerium für Ernährung und Landwirtschaft //',
	'Bundesanstalt für Landwirtschaft und Ernährung //',
	'IN FORM - Deutschlands Initiative für gesunde Ernährung und mehr Bewegung',
	'IN FORM - Deutschlands Initiative für gesunde Ernährung und mehr Bewegung',
	'Korbinian Achternbusch',
	'feel ! munich dry gin',
	'Korbinian Achternbusch',
	'Safran & Family',
	'Safran & Family',
	'Historische Senfmühle Monschau',
	'Breumo GmbH & Co. KG',
	'Senfmühle Monschau Breumo',
	'Switzerland Cheese Marketing GmbH',
	'Switzerland Cheese Marketing',
	'HACO d. Gschnitzer Franz Josef',
	'CASOLIVO',
	'boozeME GmbH',
	'boozeME',
	'Endlich wos Gscheid’s',
	'Endlich wos Gscheid’s',
	'Privatkellerei Christian und Raimund Burda GmbH',
	'Privatkellerei Christian und Raimund Burda',
	'Francesco Piscopo',
	'Francesco Piscopo',
	'Mariensteiner Brauhaus',
	'Mariensteiner Brauhaus',
	'SMOKE & WHISKY',
	'Whisk(e)y & Lifestyle GmbH',
	'SMOKE & WHISKY',
	'Extrem Lecker GbR',
	'Sebastien Scibetta',
	'Extrem Lecker',
	'SAN VINO',
	'S. Hebestreit',
	'SAN VINO',
	'MadaSpice GbR',
	'Andreas & Lalasoa Ruckdeschel',
	'MadaSpice',
	'Brauerei Ametsbichler',
	'Brauerei Ametsbichler',
	'Huber Winklhof GbR',
	'Huber Winklhof',
	'Winzerfamilie Artner GmbH',
	'Winzerfamilie Artner',
	'Perola GmbH',
	'Perola',
	'Nicolas Magurno',
	'Nicolas Magurno',
	'Aloe Vera Service',
	'Wolf & Denninger Gbr.',
	'Aloe Vera Service',
	'Ludwig Stocker',
	'Hofpfisterei GmbH',
	'Ludwig Stocker Hofpfisterei',
	'Pezzetta S.r.l.',
	'Pezzetta S.r.l.',
	'Bäckerei Konditorei Traublinger GmbH',
	'Bäckerei Konditorei Traublinger',
	'MÜHLHÄUSER GmbH',
	'MÜHLHÄUSER GmbH',
	'Weingut Walter Strub',
	'Weingut Walter Strub',
	'Stanescu  Constantin',
	'Antica Norcineria',
	'Stanescu',
	'Gianna Reina',
	'Gianna Reina',
	'Azafran GmbH',
	'Azafran',
	'BIOBEE',
	'Claudia Perle',
	'BIOBEE Claudia Perle',
	'Weingut Schlossmühle Dr. Höfer',
	'Schlossmühle Dr. Höfer',
	'BISTROTEA H&V GmbH & Co. KG',
	'BISTROTEA H&V',
	'SHIMODOZONO INTERNATIONAL GMBH',
	'KEIKO - SHIMODOZONO INTERNATIONAL',
	'Beri Laetitia',
	'Saveurs de Provence',
	'Beri Laetitia',
	'Apostel-Kräuter',
	'Naturprodukte',
	'Apostel-Kräuter',
	'GUT ZUM LEBEN',
	'Nahrungsmittel von Feld',
	'und Hof GmbH',
	'Gut zum Leben',
	'PepperPark GmbH',
	'PepperPark',
	'C.B.TEX SRL',
	'I Salumi del Cappellaio',
	'C.B.TEX SRL',
	'Kunstmühle Hofmeir - backdeinbrot',
	'Kunstmühle Hofmeir',
	'All Orient GmbH',
	'All Orient',
	'Wein- und Obstgut Born',
	'Wein- und Obstgut Born',
	'Weinbau Tremmel',
	'Herr',
	'Dinkelbäcker Dümig e.K.',
	'Dinkelbäcker Dümig',
	'FOTOGAMA UAB',
	'Šokolado namai',
	'FOTOGAMA UAB',
	'Chayou Ltd. - Japanese Tea Garden',
	'Chayou Ltd.',
	'Bayerisches Staatsministerium',
	'für Ernährung, Landwirtschaft und Forste',
	'alp Bayern',
	'Bayerisches Staatsministerium',
	'Weingut Jürgen Dostert',
	'Weingut Jürgen Dostert',
	'Maestrani',
	'Schweizer Schokoladen AG',
	'Maestrani',
	'Lindauer Bodensee-Fruchtsäfte GmbH',
	'Lindauer Bodensee-Fruchtsäfte',
	'YOLOTL Sabor de México',
	'YOLOTL',
	'Bad Reichenhaller Mineralwasser',
	'GmbH & Co. KG',
	'Bad Reichenhaller Mineralwasser',
	'AnaVita Naturkost GmbH',
	'AnaVita Naturkost',
	'Cristina Sferrazzo',
	'Cristina Sferrazzo',
	'Bergader Privatkäserei GmbH',
	'Bergader Privatkäserei',
	'Bräu im Moos',
	'Brauereigasthof und Brauerei',
	'Bräu im Moos',
	'Burgis GmbH',
	'Burgis',
	'KRIEGL ESSIG',
	'Gärungsessigbrauerei',
	'KRIEGL ESSIG',
	'Rudolf Payer',
	'Rudolf Payer',
	'Andechser Molkerei Scheitz GmbH',
	'Andechser Molkerei Scheitz',
	'Klosterbrauerei Baumburg GmbH & Co. KG',
	'Klosterbrauerei Baumburg',
	'Auerbräu GmbH',
	'Auerbräu GmbH',
	'Private Alpenbrauerei',
	'Bürgerbräu Bad Reichenhall',
	'Brauerei Bürgerbräu',
	"Sultan's Palace",
	'Mustafa Eren',
	"Sultan's Palace",
	'Ewald und Cornelia Schönhofer',
	'Winzerhof Schönhofer',
	'Winzerhof Schönhofer',
	'Landesvereinigung der Bayerischen Milchwirtschaft e.V.',
	'Landesvereinigung der Bayerischen Milchwirtschaft',
	'Herrmannsdorfer Landwerkstätten',
	'Glonn GmbH & Co. KG',
	'Herrmannsdorfer Landwerkstätten Glonn',
	'Schamel Meerrettich GmbH & Co. KG',
	'Schamel Meerrettich',
	'Weingut Ludwig Schmitt',
	'Weingut Ludwig Schmitt',
	'KUNSTMÜHLE REISGANG',
	'JOSEF SCHELLER GMBH',
	'KUNSTMÜHLE REISGANG',
	'Weingut Ernst Popp KG',
	'Weingut Ernst Popp',
	'Weingut Leininger',
	'Weingut Leininger',
	'Weingut Markus Schneider',
	'Weingut Markus Schneider',
	'MVS Milchvermarktungs GmbH',
	'sternenfair',
	'MVS Milchvermarktung',
	'Privatbrauerei Schweiger GmbH&CoKG',
	'Privatbrauerei Schweiger',
	'Schlossbrauerei Stein',
	'Wiskott GmbH & Co KG',
	'Schlossbrauerei Stein',
	'Neumarkter Lammsbräu',
	'Gebr. Ehrnsperger KG',
	'Neumarkter Lammsbräu',
	'Schlossbrauerei Herrngiersdorf KG',
	'Schlossbrauerei Herrngiersdorf',
	'Weingut Hirn & HUNDERTWASSER-Shop',
	'Weingut Hirn',
	'ULIBIS.COM',
	'Ulrich Simeth & Bianca Kempkes GbR',
	'ULIBIS.COM',
	'CAESAR & CAESAR',
	'CAESAR & CAESAR',
	'Pralinenschule',
	'Kerstin Spehr',
	'Pralinenschule Kerstin Spehr',
	'M.D.F. Formaggi S.r.l.',
	'M.D.F. Formaggi',
	'Schroth´s Spezialitäten GmbH',
	'Schroth´s Spezialitäten',
	'Flori´s Kaffeewagerl',
	'Flori´s Kaffeewagerl',
	'Hofsennerei Besler',
	'Hofsennerei Besler',
	'Holzofenbäckerei Schroth GmbH',
	'Holzofenbäckerei Schroth',
	'Wildbräu Grafing GmbH',
	'Wildbräu Grafing',
	'Weingut Reiss',
	'Christian Reiss',
	'Weingut Reiss',
	'Weingut Mönchshof Hugo Roth',
	'Weingut Mönchshof Hugo Roth',
	'Weingut Schwab',
	'Weingut Schwab',
	'Weingut Martin Göbel',
	'Weingut Martin Göbel',
	'Weingut Trockene Schmitts',
	'Paul & Bruno Schmitt',
	'Weingut Trockene Schmitts',
	'Cadenhead´s Whisky Market',
	'Cadenhead´s Whisky Market',
	'Dieter Kirsch',
	'Kirsch Whisky - The House of Whiskies',
	'Offizieller Importeur Signatory Vintage Scotch Whisky Co. Ltd.',
	'Kirsch Whisky',
	'Südostbayerischer Verband der Obst',
	'und Kleinbrenner e.V',
	'Verband der Obst und Kleinbrenner',
	'GWF Winzerkeller Randersacker',
	'GWF Winzerkeller Randersacker',
	'WHISKY FOR LIFE',
	'WHISKY FOR LIFE',
	'Whiskydestillerie "Blaue Maus"',
	'Firma Robert Fleischmann',
	'Whiskydestillerie "Blaue Maus" Firma Robert Fleischmann',
	'Irish Whiskeys',
	'Irish Whiskeys',
	'Diversa Spezialitäten GmbH',
	'Diversa Spezialitäten',
	'Bremer Spirituosen Contor GmbH',
	'Bremer Spirituosen Contor',
	'Pernod Ricard Deutschland GmbH',
	'Pernod Ricard',
	'Gradls Whiskyfässla',
	'Gradls Whiskyfässla',
	'Münchner Kindl Senf',
	'Münchner Kindl Senf',
	'DIVINO Nordheim Thüngersheim eG',
	'DIVINO',
	'Brauerei Aying',
	'Franz Inselkammer KG',
	'Ayinger Privatbrauerei',
	'Süddeutsche Zeitung GmbH',
	'Süddeutsche Zeitung',
	'Olio Mancuso',
	'Olio Mancuso',
	'DbV-Muenchen UG',
	'DbV-Muenchen',
	'3fruits & friends GmbH',
	'3fruits & friends',
	'Münchner Glückskindl GmbH',
	'Münchner Glückskindl',
	'Fürstenhof GmbH',
	'Bio-Hofkäserei Fürstenhof',
	'Bio-Hofkäserei Fürstenhof',
	'Bäckerei Lieberwirth',
	'Bäckerei Lieberwirth - Die Kekselmacher',
	'Hans Gasser GmbH',
	'Hans Gasser',
	'Wandlbeck UG',
	'Wandlbeck',
	'Stefan Potzinger Weine GmbH',
	'Stefan Potzinger Weine',
	'Ricola AG',
	'Ricola AG',
	'Mister Misses M.-Confiserie & Lifestyle',
	'Mister Misses M.',
	'Bio Terra Markt',
	'Bio Terra Markt',
	'Tokajer Essig',
	'Tokajer Essig',
	'Nara Food',
	'Georg Huber',
	'Nara Food',
	'Christine Berger GmbH & Co. KG',
	'Christine Berger',
	'Olli Stich',
	'Käsemanufaktur',
	'Olli Stich Käsemanufaktur',
	'Manuela Siess',
	'Tiroler Hofladen',
	'Tiroler Hofladen',
	'Alan Trade S.R.L.S.',
	'Alan Trade',
	'Furco Biscotti di Giovanni Oliva',
	'Furco Biscotti',
	'Bettinas Keimbackstube',
	'Bettinas Keimbackstube',
	'Dr. Homer Berndl',
	'Dr. Homer Berndl',
	'HelloFresh Deutschland SE & Co. KG',
	'HelloFresh',
	'HOPFA  Dr. Kurt Berndl e.K.',
	'HOPFA',
	'Münchner Spirituosen GmbH',
	'Münchner Spirituosen',
	'Consorzio Vacche Rosse Soc. Coop. Agr.',
	'Consorzio Vacche Rosse',
	'TuttoBono',
	'Toskanische Spezialitäten',
	'TuttoBono',
	'olive joy',
	'olive joy',
	'Weingut Vollmer',
	'Weingut Vollmer',
	'Vittorio Canu',
	'Vittorio Canu',
	'Bio-Hofbäckerei Mauracher GmbH',
	'Bio-Hofbäckerei Mauracher',
	'Biscottificio di Migliana SRL',
	'Antico Forno Santi',
	'Biscottificio di Migliana',
	'MARABISSI S.r.l.',
	'MARABISSI',
	'Genusskellerei',
	'Genusskellerei',
	'Foodist GmbH',
	'Foodist',
	'Grizzly Snacks UG (haftungsbeschränkt)',
	'Grizzly Snacks',
	'Mansuris',
	'Mansuris',
	'Lukullium - kulinarische Entdeckungen',
	'Lukullium',
	'Spicebar GmbH',
	'Spicebar',
	'Allgäuer Wanderimkerei',
	'Allgäuer Wanderimkerei',
	'SCHREYÖGG GmbH',
	'Kaffeerösterei',
	'SCHREYÖGG',
	'Speckladele',
	'Speckladele',
	'Profanter Natur-Backstube',
	'Profanter',
	'Loacker Deutschland GmbH',
	'Loacker Deutschland',
	'Bäckerei Konditorei Moser',
	'Bäckerei Konditorei Moser',
	'Metzgerei Steiner OHG',
	'Metzgerei Steiner',
	'gustaio',
	'gustaio',
	'Wildlachs Strobl Feinkost GbR',
	'Wildlachs Strobl',
	'Herbert Sommer',
	'Weingut Rebhof Sommer',
	'Weingut Rebhof Sommer',
	'Bäckerei Konditorei Cafe Spring',
	'Kai Goldmann',
	'Bäckerei Konditorei Cafe Spring',
	'Irmtraut Melk',
	'Irmtraut Melk',
	'Viktor und Andreas Kofler O.H.G.',
	'Viktor und Andreas Kofler',
	'AZ.AGR.CA DER FER DI FANTAGUZZI',
	'IOLE ROSA',
	'AZ.AGR.CA',
	'Gebrüder Mayer GmbH & Co.KG',
	'Gebrüder Mayer',
	'Greekbio',
	'Konstantinos Panidis',
	'Greekbio',
	'Wild & Wild GbR -',
	'Wildkaffee Rösterei',
	'Wild & Wild',
	'REGION OF CENTRAL GREECE',
	'CENTRAL GREECE',
	'DIVINUM - KOUTLOUMBASI ELENI Ltd.',
	'DIVINUM',
	'Weingut Elfenhof',
	'Weingut Elfenhof',
	'Studio Schumm GmbH',
	'STUDIOSCHUMM',
	'TVBD Sulmtal Sausal -',
	'Südsteirisches Weinland',
	'TVBD Sulmtal Sausal',
	'Sierra Madre GmbH',
	'Sierra Madre',
	'Valinch & Mallet Ltd',
	'Valinch & Mallet',
	'whiskymax import',
	'whiskymax',
	'nearBees GmbH',
	'nearBees',
	'ARUNDA GmbH',
	'ARUNDA',
	'ABONAUTEN UG',
	'ABONAUTEN',
	'Brauerei und Brennerei Silbernagl e.K.',
	'Manfred Silbernagl',
	'Brauerei und Brennerei Silbernagl',
	'Ali Khedija',
	'Weingut Henri Maire',
	'Ali Khedija Weingut',
	'Au comptoir d’ André',
	'Inh. André Chateigner',
	'Au comptoir d’ André',
	'Naturkäserei TegernseerLand e.G.',
	'Naturkäserei TegernseerLand',
	'Bier-Honig Neber-Hagemann',
	'Bier-Honig',
	'BENLEA GbR',
	'BENLEA',
	'Kondrauer Mineral- und',
	'Heilbrunnen GmbH & Co. KG',
	'Kondrauer Mineral- und Heilbrunnen',
	'ARONIALAND',
	'DAS ORIGINAL AUS ÖSTERREICH',
	'ARONIALAND',
	'Tenso Suppliers',
	'Tenso Suppliers',
	'MY HOME MADE S.R.L.',
	'MY HOME MADE',
	'Moet Hennessy Deutschland GmbH',
	'Moet Hennessy',
	'THE DUKE Destillerie',
	'Maximilian Schauerte',
	'THE DUKE',
	'HERRNBRÄU GmbH',
	'HERRNBRÄU',
	'Western Blue e.K.',
	'Western Blue',
	'Brauerei S. Riegele',
	'Inh. Riegele KG',
	'Brauerei S. Riegele',
	'EFAG GmbH & Co. KG',
	'EFAG',
	'Picasso Kulinarisch - Gewürze & Feines',
	'Picasso Kulinarisch',
	'Nature Gift SIA',
	'Nature Gift',
	'Salomon BAAR',
	'Salomon BAAR',
	'Hofer Manufaktur',
	'Hofer Manufaktur',
	'Azienda Agricola Carrozzo Alessandro',
	'Azienda Agricola',
	'Best Steak',
	'FOOD & LIFE',
	'Best Steak',
	'Genusswerkstatt Bayern',
	'FOOD & LIFE',
	'Genusswerkstatt Bayern',
	'Kaffeehaus',
	'FOOD & LIFE',
	'Kaffeehaus',
	'Kochbühne',
	'FOOD & LIFE',
	'Kochbühne',
	'HEILAND Liqueur',
	'HEILAND',
	'KAPRONCA D.O.O.',
	'KAPRONCA D.O.O.',
	'Able Catering GbR',
	'Able Catering',
	'Vegetalis Catering',
	'Vegetalis Catering',
	'PrimoVino',
	'Gerhard Wagner',
	'PrimoVino',
	'SUPERDRINK GmbH',
	'SUPERDRINK',
	'DE CAÑA - Panela by MEISEL FINE GOODS GmbH',
	'DE CAÑA',
	'GIESINGER BIERMANUFAKTUR &',
	'SPEZIALITÄTENBRAUGESELLSCHAFT MBH',
	'GIESINGER BIERMANUFAKTUR',
	'K.L.Ni Promotion Co.',
	'K.L.Ni Promotion Co.',
	'Rehorik Regensburger Kaffeerösterei',
	'Rehorik',
	'Confiserie Simon',
	'Confiserie Simon',
	'Beefer Grillgeräte GmbH',
	'Beefer Grillgeräte GmbH',
	'I Dolci Del Ciclope S.r.l.s.',
	'I Dolci Del Ciclope S.r.l.s.',
	'FIRE&FOOD Verlag GmbH',
	'FIRE&FOOD',
	'Jarfood GmbH',
	'Jarfood GmbH',
	'KYRALAKI THEONYMFI',
	'KYRALAKI THEONYMFI',
	'Isarkindl OHG',
	'Isarkindl OHG',
	'Münchner Girgbräu GmbH',
	'Haderner Bräu München',
	'Münchner Girgbräu GmbH Haderner Bräu München',
	'Single Malt Connoisseur`s',
	'Club München',
	'Single Malt Connoisseur`s Club München',
	'KNUSPERREICH',
	'KNUSPERREICH',
	'American Heritage',
	'Inh. Sabine Ryan',
	'American Heritage',
	'Johannes Roll und Murat Coban GbR',
	'Jomu',
	'Johannes Roll und Murat Coban GbR Jomu',
	'Lunch Vegaz GmbH',
	'Lunch Vegaz GmbH',
	'Andrea Vestri',
	'European Wine Education',
	'Andrea Vestri European Wine Education',
	'Roll Baby',
	'Roll Baby',
	'Agria dei F.lli Aliani ss Agricola',
	'Agria dei F.lli Aliani ss Agricola',
	'Pars Safran GmbH',
	'Pars Safran GmbH',
	'Slyrs Destillerie GmbH & Co. KG',
	'Slyrs Destillerie GmbH & Co. KG',
	'Fun of Europe Handels GmbH',
	'Fun of Europe Handels GmbH',
	'Prineus GmbH',
	'Prineus GmbH',
	'Esther John KG',
	'Esther John KG',
	'Paulikocht GmbH',
	'Paulikocht GmbH',
	'Kraftfleisch GmbH',
	'Kraftfleisch GmbH',
	'Woody’s - Edles aus Holz',
	'Woody’s - Edles aus Holz',
	'Ben Jacobs',
	'Simple Jerky',
	'Ben Jacobs Simple Jerky',
	'DCI Cannabis Institut GmbH',
	'HANF der etwas andere Bioladen',
	'DCI Cannabis Institut GmbH HANF der etwas andere Bioladen',
	'Love My Little Kitchen',
	'Love My Little Kitchen',
	'Rehmbrand Medienservice GmbH',
	'Rehmbrand Medienservice GmbH',
	'Bioteaque GmbH & CO.KG',
	'Bioteaque GmbH & CO.KG',
	'Philip Morris GmbH',
	'Philip Morris GmbH',
	'REISEKULTOUREN GmbH',
	'REISEKULTOUREN GmbH',
	'I sapori di Sicilia Group',
	'I sapori di Sicilia Group',
	'Glasmanufaktur Michael Greiner',
	'Glasmanufaktur',
	'TLS-Dachfenster',
	'TLS-Dachfenster',
	'Holz das Leben (Kunsthandwerk)',
	'Stumpf GbR',
	'Holz das Leben',
	'INOTHERM d.o.o.',
	'INOTHERM',
	'Swiss Plus AG',
	'Swiss Plus',
	'Lehner Haus GmbH',
	'Lehner Haus',
	'Slowroom Katarzyna Hiller',
	'Slowroom',
	'Allianz Generalvertretung Andreas Weidl',
	'Allianz Generalvertretung',
	'Whirlpool & Living GmbH',
	'Whirlpool & Living',
	'Günther Weinz GmbH',
	'Günther Weinz',
	'Jolanda Jackeline Proano Flores',
	'Jolanda Jackeline',
	'Vodafone Kabel Deutschland GmbH',
	'Vodafone Kabel Deutschland',
	'C-Motive GmbH',
	'C-Motive',
	'PEMA S.R.L',
	'PEMA S.R.L',
	'SchlafOptimal',
	'München',
	'SchlafOptimal',
	'Servicestelle der Bayerische Staatsregierung',
	'Servicestelle der Bayerische Staatsregierung',
	'AGO Algen + Moosentferner',
	'AGO Algen + Moosentferner',
	'Seebauer -',
	'Die Schlafraumeinrichter OHG',
	'Seebauer',
	'Planeta, Haushaltsgeräte GmbH & Co. KG',
	'Planeta',
	'Schimmel-Hex',
	'Schimmel-Hex',
	'Filzicus, Qualität aus Merino-Filz',
	'Filzicus',
	'Waa.Lea GmbH',
	'Waa.Lea GmbH',
	'Umar Carpet Factory',
	'Umar Carpet Factory',
	'Leder Mainhardt',
	'Gerhard Mainhardt',
	'Leder Mainhardt',
	'modasafe -',
	'eine Marke der Modahum GmbH',
	'modasafe',
	'DaMi Wohn- und Schlafsysteme',
	'Edgar Schlichter',
	'DaMi Wohn- und Schlafsysteme',
	'Tupperware',
	'Bezirkshandlung Landshut',
	'Tupperware',
	'Lotform AG',
	'Lotform',
	'DOMUS-SANA',
	'Patcharin Neumayr',
	'DOMUS-SANA',
	'Schmidt Harmonikaerzeugung GmbH',
	'Schmidt Harmonikaerzeugung',
	'Sky Deutschland Fernsehen GmbH & Co. KG',
	'Sky Deutschland',
	'SO COSY',
	'SO COSY',
	'ASS - Überdachungen',
	'ASS-Überdachungen',
	'Möbel Schwarz oHG',
	'Möbel Schwarz',
	'Creazioni in Cucina',
	'Creazioni in Cucina',
	'Singhammer Bodensysteme GmbH',
	'Singhammer',
	'DELANA e.U.',
	'DELANA',
	'Quellweich',
	'M Eckstein GmbH',
	'Quellweich GmbH',
	'Handelsagentur Nicolle Seidel',
	'Nicolle Seidel',
	'Gundel Pfannen I Das Original seit 1972',
	'Niederschweiberer & Schenk GbR',
	'Gundel-Pfannen',
	'Wärmegrad GmbH',
	'Wärmegrad GmbH',
	'Sano-Vital',
	'Sano-Vital',
	'Bert Bautechnik GmbH & Co. KG',
	'Bert Dachfenster',
	'Küchenspezialist Hiller GmbH',
	'Küchenspezialist Hiller',
	'HAnRo Montageservice',
	'Rost Andreas',
	'HAnRo',
	'VÖROKA GmbH',
	'VÖROKA GmbH',
	'Vita-Via',
	'Ebert, Hierl, Languth GbR',
	'Vita-Via',
	'Antiquitäten Sauff',
	'Antiquitäten Sauff',
	'Maria Barleben',
	'Barleben-Handspielpuppen',
	'Maria Barleben',
	'Natura Design',
	'Natura Design',
	'H&H Infrarot Tiefenwärmekabinen',
	'Wimmer OHG',
	'H&H Infrarot Tiefenwärmekabinen',
	'GRANDER Wasserbelebung Ges.m.b.H.',
	'GRANDER',
	'UNIPOR Ziegel Marketing GmbH',
	'UNIPOR',
	'Blaudruckwerkstatt',
	'Henkenjohann & Sander e.K.',
	'Blaudruckwerkstatt',
	'Oberhauser Bau-Systeme GmbH',
	'Oberhauser Bau-Systeme GmbH',
	'Nappa Lux Lederwaren GmbH',
	'Nappa Lux',
	'Unimatic Vertriebs-GmbH',
	'Unimatic',
	'Invida GmbH',
	'Invida GmbH',
	'Meni - Mein Niveau',
	'Terrassenüberdachungen',
	'Meni - Mein Niveau',
	'RETTL 1868 Kilts & Fashion e.U.',
	'RETTL 1868',
	'IVG Handels, Messe, Immobilien und',
	'Bauträgergesellschaft mbH',
	'IVG',
	'Tesla Germany GmbH',
	'Tesla Germany GmbH',
	'Gazarch Mongolia',
	'Gazarch Mongolia',
	'TecPoint GmbH',
	'TecPoint',
	'Ursprung UG & Co. KG',
	'Ursprung',
	'WARIMEX Waren-Import-Export Handels GmbH',
	'WARIMEX',
	'Simply Best GmbH',
	'Simply Best GmbH',
	'HÖRGERÄTE SEIFERT GMBH',
	'HÖRGERÄTE SEIFERT',
	'Bella Casa',
	'Mediterranes Wohnen',
	'Bella Casa',
	'mk.art',
	'mk.art',
	'puralpina ag',
	'puralpina ag',
	'Biostein Vertriebs GmbH',
	'Biostein',
	'Bienen-Schloß-Manufaktur GbR',
	'Schloß Warlitz',
	'Bienen-Schloß-Manufaktur',
	'ABG/Bau Beratung Boldt GmbH',
	'ABG/Bau Beratung Boldt',
	'Hafnerhof Kachelofenbau GmbH',
	'Hafnerhof',
	'Indra Metallwaren',
	'Indra Metallwaren',
	'Multikon GmbH',
	'Multikon GmbH',
	'Löwen-Stein',
	'Jürgen Borchert',
	'Löwen-Stein',
	'Alexander Schmidt',
	'Mobiler Vertrieb',
	'Alexander Schmidt',
	'XPOUF- Expand Home Design SAS',
	'XPOUF',
	'VARIO-BAU Fertighaus GmbH',
	'VARIO-HAUS',
	'ORIENTE SRL',
	'OLD TEAK DIFFUSION',
	'ORIENTE SRL',
	'Gottwald´s Bäderwerkstatt GmbH',
	'Gottwald´s Bäderwerkstatt',
	'Edelholzstifte & Weihnachtskrippen',
	'Edelholzstifte Ursula & Heribert Lechner',
	'Hut Brunhuber',
	'Inhaberin: Monika Voggenauer',
	'Hut Brunhuber',
	'Cervotec GmbH & Co. KG - Fahrradgaragen',
	'Cervotec Fahrradgaragen',
	'Regierung von Oberbayern',
	'Gewerbeaufsichtsamt',
	'Gewerbeaufsichtsamt Oberbayern',
	'JARO-Design',
	'JARO-Design',
	'Kuchler Konzepte aus Holz, Glas & Metall',
	'Kuchler Konzepte aus Holz, Glas & Metall',
	'BDSK Handels GmbH & Co. KG',
	'XXXLutz Aschheim',
	'BDSK Handels GmbH & Co. KG XXXLutz Aschheim',
	'Der Ofenbaumeister',
	'Inhaber: Hendrik Kraus',
	'Der Ofenbaumeister',
	'Jumis',
	'Inh. Sanita Smuidrina-Keil',
	'Jumis',
	'BTM',
	'Fred Oliver Braunesberger Handels GmbH',
	'BTM GmbH',
	'GP Direct GmbH',
	'GP Direct',
	'Leitner Sicherheits-, Überwachungs- & Elektrotechnik',
	'Geschäftsinhaber: Thomas Leitner',
	'Leitner',
	'Luisa Hahn',
	'Mode- und Lederdesign',
	'Luisa Hahn',
	'Chiemsee Öfen GbR',
	'Chiemsee Öfen',
	'Hüsler Nest Vertriebs GmbH',
	'Hüsler Nest',
	'Lounge & Penthouse',
	'Home Couture PGmbH / Traumsofa',
	'Lounge & Penthouse',
	'Mir Kashmir Art',
	'Mir Kashmir Art',
	'Garten Primus GmbH',
	'Garten Primus',
	'Chiemgauer Holzhaus',
	'LSP Holzbau GmbH & Co. KG',
	'Chiemgauer Holzhaus',
	'Rotel GmbH',
	'Rotel GmbH',
	'Cashmeer',
	'Cashmeer',
	'Alpina Sonnenschutz GmbH',
	'Alpina Sonnenschutz',
	'Alukov Deutschland GmbH',
	'Alukov Deutschland',
	'Cooklife e.K.',
	'geniale Ideen für die Küche',
	'Cooklife e.K.',
	'Wimmer schneidert',
	'Inh. Stefan Wimmer',
	'Wimmer schneidert',
	'Donnerberg',
	'Donnerberg',
	'Reitmaier Balkon GmbH',
	'Reitmaier',
	'Margaretha Design',
	'Gerlinde Decker',
	'Margaretha Design',
	'H&D AG',
	'H&D AG',
	'HK-Marketing - Harry Kreutz',
	'HK-Marketing',
	'ERING - Gartentechnik',
	'ERING',
	'CPS Deutschland',
	'Creative Promotion Service Deutschland',
	'CPS Deutschland',
	'Manfred Radspieler',
	'SIT & RELAXX + Zubehör',
	'SIT & RELAXX',
	'Alfons Diefenthaler',
	'Handelsvertretung',
	'Alfons Diefenthaler Handelsvertretung',
	'Edmund Ahrer e. U.',
	'Wellness & Wohnen',
	'Edmund Ahrer e. U.',
	'Siesta Bettenstudio',
	'Inhaber Istvan Poocza',
	'Siesta Bettenstudio',
	'Kinskofer Holzhaus GmbH',
	'Kinskofer Holzhaus',
	'Bauer Bauelemente GmbH & Co. KG',
	'Bauer Bauelemente',
	'Gaulhofer Deutschland GmbH & Co. KG',
	'Fenster und Türen',
	'Gaulhofer Deutschland GmbH & Co. KG Fenster und Türen',
	'RÖSLE GmbH & Co. KG',
	'RÖSLE GmbH',
	'Böcker Maschinenwerke GmbH',
	'Böcker Maschinenwerke',
	'Haberl Massivholztüren',
	'Markus Haberl e.U.',
	'Haberl Massivholztüren',
	'Hans Moes',
	'DesignforLiving',
	'DesignforLiving',
	'DESJOYAUX POOLS FREISING GmbH',
	'DESJOYAUX POOLS FREISING GmbH',
	'Dshamila',
	'Dshamila',
	'X-OVER',
	'creative pool distribution GmbH',
	'X-OVER',
	'BDSK Handels GmbH & Co. KG',
	'XXXLutz Hiendl Regensburg',
	'BDSK Handels GmbH & Co. KG Filiale Hiendl XXXL Regensburg',
	'not couture',
	'STADLER',
	'STADLER',
	'Fegel Promotion',
	'Inh. Jürgen Fegel',
	'Fegel Promotion',
	'Benedikt Preisinger GmbH',
	'-Der Ofenbauer-',
	'-Der Ofenbauer-',
	'GSB Haus der Sicherheitstechnik',
	'GSB',
	'Opal Dreams',
	'Opal Dreams',
	'RUKU Tore - Türen GmbH',
	'RUKU Tore - Türen',
	'leguano GmbH',
	'leguano GmbH',
	'Schneider GmbH',
	'Das Gute für Ihr Wohlbefinden',
	'Schneider GmbH',
	'HERMAPRO GmbH',
	'Gartenkamine aus Edelstahl',
	'Bioethanolkamine',
	'Feuerstellen',
	'HERMAPRO',
	'Exclusives Wohnen Nagler',
	'H. P. Nagler',
	'Exclusives Wohnen Nagler',
	'M-One International Co. Ltd.',
	'M-One International',
	'Eurobalkone & Zäune',
	'Oliver Dombek',
	'Eurobalkone & Zäune',
	'Eckl Kamine & Solar',
	'GmbH & Co. KG',
	'Eckl Kamine & Solar',
	'Bundesamt für das Personalmanagement der Bundeswehr',
	'Gold mit antiken Fundstücken',
	'Gold Fundstücke',
	'LEPI Leo Prinoth GmbH',
	'LEPI Leo Prinoth',
	'HARTL HAUS Holzindustrie Vertriebsges. f. Fertighäuser mbH',
	'HARTL HAUS',
	'Provera Warenhandels GmbH',
	'Provera',
	'Ishanjay Expo',
	'Ishanjay Expo',
	'Rudi Ax GmbH',
	'Rudi Ax GmbH',
	'hochbeet.com',
	'hochbeet.com',
	'Samina Deutschland GmbH',
	'Filiale Samina München',
	'SAMINA München',
	'Schreinerei Faltermeier',
	'Schreinerei Faltermeier',
	'VSB Förster GmbH',
	'ISP Insektenschutzprofi',
	'VSB Förster GmbH',
	'Ganesh Handicraft',
	'Ganesh Handicraft',
	'ricana Oxygen e.K.',
	'ricana Oxygen',
	'bau-ko GmbH',
	'Fensterservice',
	'bau-ko GmbH',
	'Weizel GmbH',
	'Weizel GmbH',
	'Elisabeth Wiechmann',
	'Baubiologie',
	'Elisabeth Wiechmann Baubiologie',
	'SPS-SYSTEME Lomberg',
	'SPS-SYSTEME',
	'Shakeel Handicrafts',
	'Shakeel Handicrafts',
	'Lellinger GmbH',
	'Super-fix',
	'Lellinger GmbH',
	'kds GmbH Komplette Dachsanierung',
	'Guido Baeyens',
	'kds GmbH Komplette Dachsanierung Guido Baeyens',
	'kbs GmbH Komplette Bausanierung',
	'kbs GmbH',
	'Christine Vitzthum',
	'Werkstatt für Schmuck',
	'Christine Vitzthum',
	'Thuyen Quyen Co. Ltd.',
	'Thuyen Quyen',
	'Daniel Hiller',
	'Schmuckatelier - Schmuckphantasien',
	'Daniel Hiller',
	'Matrotec GmbH',
	'Matrotec',
	'ATILA GmbH',
	'ATILA GmbH',
	'KD WASSERTECHNIK GmbH',
	'KD WASSERTECHNIK',
	'Schmuck & Steine',
	'Schmuck & Steine',
	'DILA Handel GmbH',
	'DILA',
	'Wohnfabrik Pforzheim',
	'Wohnfabrik Pforzheim',
	'NUAD® Öl - OneForLove Ltd.',
	'NUAD®',
	'Anrei-Reisinger GmbH',
	'Anrei-Reisinger GmbH',
	'Wickis Grillhütten by Scandinavic Wood Art',
	'Wickis Grillhütten',
	'MAPE Handel GmbH',
	'MAPE GmbH',
	'Nähmaschinen Christmann oHG',
	'Inh. Andreas und Michael Christmann',
	'Nähmaschinen Christmann',
	'Chinar Crafts',
	'Chinar Crafts',
	'TOPGRÜN 5',
	'Uwe Kienzler',
	'TOPGRÜN 5',
	'watercat gmbh',
	'watercat gmbh',
	'Robot GmbH',
	'Robot GmbH',
	'Lebensraum Holz GmbH',
	'Lebensraum Holz GmbH',
	'DiHa GmbH - Dichtes Haus',
	'DiHa GmbH',
	'Hydrosoft c/o Olymp Werk GmbH',
	'Die Wärme aus Tirol',
	'Hydrosoft c/o Olymp Werk',
	'Topdream GmbH',
	'Topdream',
	'Pittrof GmbH',
	'Pittrof GmbH',
	'Heim & Haus Vertriebsgesellschaft',
	'für Kunststoffenster und-rolläden mbH',
	'Heim & Haus',
	'KÄFER BÄDER',
	'– Komplettbäder/Badrenovierung /Barrierefreie Bäder',
	'Käfer Bäder',
	'Eurobond Technologies OG',
	'Eurobond Technologies',
	'PRS Bautenschutz und',
	'Sonnenschutz-Vertriebs GmbH',
	'PRS GmbH',
	'MEUBLES BEAULIEU SARL',
	'Société ZIMMERMANN',
	'MEUBLES BEAULIEU',
	'cleenbo Ziad Assassa',
	'cleenbo',
	'SRS Solartechnik GmbH',
	'SRS Solartechnik',
	'DANKÜCHEN Rosenheim',
	'Hans Winhart',
	'DANKÜCHEN',
	'AMC Alfa Metalcraft Corporation',
	'Handelsgesellschaft mbH',
	'AMC Alfa Metalcraft Corporation',
	'WABEG',
	'Wasseraufbereitungssysteme',
	'WABEG',
	'FS Handelsgesellschaft mbH',
	'FS Handelsgesellschaft',
	'MATTERN & Co. GmbH',
	'Aluminium- und Edelstahl-Verarbeitung',
	'MATTERN & Co.',
	'OrthoDorn',
	'OrthoDorn',
	'Ofenshop - Heinemann Vertriebs GmbH',
	'Ofenshop',
	'STEICO SE',
	'STEICO SE',
	'IST Insektenschutztechnik GmbH',
	'IST Insektenschutztechnik',
	'roko Insektenschutz e.k.',
	'roko Insektenschutz',
	'Actual Fenster Türen Sonnenschutz GmbH',
	'Actual Fenster Türen Sonnenschutz GmbH',
	'Feldmann GmbH & Co. KG',
	'Feldmann GmbH',
	'M+S Dach- und Fassadenbau GmbH',
	'M+S GmbH',
	'Pasco Industrieklebstoffe',
	'Christian Brand',
	'Pasco Industrieklebstoffe',
	'Otto Wintergartenbau e.K.',
	'Otto Wintergartenbau',
	'Sofa Art International',
	'Leather forever',
	'Sofa Art International',
	'Niedermaier GmbH',
	'Handelsvertretung',
	'Niedermaier GmbH',
	'Best - Wellness Peter Haller',
	'Best - Wellness',
	'Walter Lahr',
	'Steinschmuck- und Juwelen-Fabrik',
	'Inh. Dieter Grämer',
	'Walter Lahr',
	'Vorwerk Deutschland Stiftung & Co. KG',
	'Geschäftsbereich Thermomix',
	'Vorwerk',
	'Hofmann Fensterzubehör Insekten & Sonnenschutz',
	'Hofmann Fensterzubehör',
	'Juchiwell Europa GmbH',
	'Juchiwell Europa',
	'Pfahler´s Whirlpool Studio',
	'Günter Pfahler e.K.',
	'Günter Pfahler e.K.',
	'Ferstl-Holz GmbH',
	'Ferstl-Holz',
	'Luft- und Wasserbetten Zentrum',
	'airvital e.K.',
	'airvital e.K.',
	'Artweger GmbH & Co. KG',
	'Artweger',
	'chairs.de',
	'chairs.de',
	'Fechner GmbH + Co. KG',
	'Klima-Sauna',
	'Fechner GmbH',
	'Hargassner GmbH',
	'Hackgut und Pelletsanlagen',
	'Deutschland',
	'Hargassner GmbH',
	'Kamin-Kassetten-Lesnik GmbH',
	'Kamin-Kassetten-Lesnik',
	'AQUA UNIMAT e.K.',
	'AQUA UNIMAT',
	'Brunner Ges.m.b.H.',
	'Heizen-Kochen-Elektro',
	'Brunner Ges.m.b.H.',
	'Dr. Doit',
	'M. Artz GmbH',
	'Dr. Doit',
	'Kroiher GmbH',
	'K&K Fenster und Wintergärten',
	'FINSTRAL Profi-Partner',
	'Kroiher GmbH K&K Fenster und Wintergärten FINSTRAL Profi-Partner',
	'Elemente',
	'Marcus Schwarzlmüller',
	'Elemente Marcus Schwarzlmüller',
	'TEKNO Gerätefabrik GmbH',
	'TEKNO',
	'Deutsche Bundesbank',
	'Filiale München',
	'Bundesbank München',
	'Riedl Aufzugbau GmbH & Co. KG',
	'Riedl Aufzugbau GmbH & Co. KG',
	'Gewa Balkonsysteme',
	'Gewa Balkonsysteme',
	'Aqualit Quellsteine GmbH',
	'Springbrunnen und Wasserspiele',
	'Aqualit Quellsteine',
	'Regnauer Hausbau',
	'GmbH & Co. KG',
	'Regnauer Hausbau',
	'Girse - design',
	'Grillkamine aus Edelstahl',
	'Girse - design',
	'InKa GmbH',
	'InKa GmbH',
	'art for living GmbH',
	'Marco Mehn',
	'art for living',
	'Muckenthaler Ergonomie Studio',
	'Muckenthaler Ergonomie',
	'Sport- und Medizintechnik',
	'Frank Hoherz',
	'Frank Hoherz',
	'Wefa-Dachreinigungssysteme',
	'Dächer und Fassaden',
	'Wefa',
	'perfecta Fenster',
	'Vertriebs- und Montage GmbH',
	'perfecta - Fenster & Türen',
	'Steam Deutschland GmbH',
	'Steam Deutschland',
	'CC-Pearls GmbH',
	'South Sea Pearl Center',
	'Abteilung Design/Antiquitäten',
	'CC-Pearls GmbH',
	'Pamir UG',
	'Pamir UG',
	'Schanz Rollladensysteme GmbH',
	'Schanz GmbH',
	'Isar-Würm-Lech',
	'IWL-Werkstätten für Behinderte Menschen GmbH',
	'Isar-Würm-Lech IWL-Werkstätten für Behinderte Menschen GmbH',
	'F.B. Zell Aktiv GmbH',
	'F.B. Zell Aktiv',
	'Karlheinz Gratzl',
	'Schmutzfangmatten Reinigungsbedarf',
	'Karlheinz Gratzl',
	'Küche und Plan Wieser GmbH',
	'wieserKÜCHEN',
	'Baukoordination',
	'Paula Vogel',
	'Baukoordination Paula Vogel',
	'Walter Frick GmbH',
	'Polstermöbel',
	'Walter Frick GmbH',
	'Schöberl - Decken und Luxusschals',
	'Schöberl',
	'Ha-Ra Adlmüller',
	'Ha-Ra',
	'Küchen Necker GmbH',
	'Küchen Necker',
	'SINGER / Helmut Hämmerle',
	'Maschinenhandels Ges.m.b.H. & Co. KG',
	'SINGER',
	'Nähzentrum Haimerl GmbH',
	'Nähzentrum Haimerl GmbH',
	'Kaupp Balkone',
	'Kaupp Balkone',
	'Holzmann Türen',
	'Treppen und Küchen',
	'Holzmann',
	'Engelbert Leichauer',
	'Engelbert Leichauer',
	'ASMO Küchen GmbH',
	'ASMO Küchen GmbH',
	'Ulrich Haake',
	'Garten- und Landschaftsbau',
	'Ulrich Haake',
	'Peter Lorenz',
	'Inh. Sven Peter Lorenz e.K.',
	'Peter Lorenz',
	'Koll-Saunabau.de',
	'Inh. Dirk Koll',
	'Koll-Saunabau.de',
	'MIRA ART GmbH',
	'Traumschwinger, Sense & Soul',
	'MIRA ART',
	'Tischlerei Wagenleitner',
	'Karl Strasser GmbH',
	'Tischlerei Wagenleitner',
	'Stukkateurmeister Florian Degmair',
	'Fassaden- und Stuckunternehmen',
	'Stukkateurmeister Degmair',
	'Christoph GmbH',
	'Dachgauben',
	'Christoph GmbH',
	'Kohler-Küchenmaschinen',
	'Herstellung und Vertrieb',
	'Kohler-Küchenmaschinen',
	'Mühldorfer GmbH & Co.KG',
	'Mühldorfer GmbH & Co.KG',
	'WEHA Wassertechnik',
	'WEHA',
	'Bachtar Kleinod Fasli & Fazli OHG',
	'Bachtar Kleinod',
	'Bayerisches Landeskriminalamt',
	'Sachgebiet 513 Prävention',
	'Foschung, Statistik',
	'Bayerisches Landeskriminalamt',
	'Delphin-Luft und Raumreinigungsgerät',
	'Alfons Eberle',
	'Delphin',
	'J. Klewer',
	'Überdachungen & Beschattung',
	'Klewer',
	'Landeshauptstadt München',
	'Baureferat - Gartenbau',
	'G 44 Ausbildung',
	'Baureferat München',
	'LINIE C Collection AG',
	'LINIE C Collection',
	'Holzwarth GmbH',
	'Fenster + Türen',
	'Holzwarth GmbH',
	'Armstark Handels GmbH',
	'Armstark Handels GmbH',
	'Erlesene Tischkultur Wolff',
	'Inh. Marius Wolff',
	'Erlesene Tischkultur Wolff',
	'Liebenswertes Gestern',
	'Inh. Helga Kraus',
	'Liebenswertes Gestern',
	'MARENO Wörle + Schaller GbR',
	'Türen - Treppen - Fenster',
	'MARENO',
	'Blum Opale',
	'Blum Opale',
	'Elke Karmann',
	'Elke Karmann',
	'Richter & Röhrig GmbH',
	'360°HzweiO',
	'Richter & Röhrig GmbH',
	'Sonnleitner Holzbauwerke',
	'GmbH & Co. KG',
	'Sonnleitner Holzbauwerke',
	'ETA Heiztechnik GmbH',
	'ETA Heiztechnik',
	'Stadtwerke München',
	'Stadtwerke München',
	'ÖkoFEN Heiztechnik GmbH',
	'ÖkoFEN',
	'Importholz Büchner KG',
	'Importholz Büchner',
	'Feuerwerkstatt',
	'Adi Krämer GmbH',
	'Feuerwerkstatt Adi Krämer',
	'Polstermöbel Fischer',
	'Max Fischer GmbH',
	'Polstermöbel Fischer',
	'Johann Lechner GmbH',
	'Holzhaus - Ziegelhaus - Gebäudemodernisierung',
	'Johann Lechner GmbH',
	'Parkett Leuthe GmbH',
	'Parkett Leuthe GmbH',
	'DRAGON',
	'Verkaufsgesellschaft mbH',
	'DRAGON Verkaufsgesellschaft mbH',
	'SiglLicht GmbH',
	'SiglLicht GmbH',
	'Ideen Küche Handels GmbH',
	'Ideen Küche',
	'Rudi Richter GmbH',
	'Fachhandel Türen und Fenster',
	'Rudi Richter GmbH Fachhandel Türen und Fenster',
	'Leeb Balkone und Zäune Niederlassung München',
	'Leeb Balkone GmbH',
	'Pfannen Harecker',
	'Inhaber: Michael Harecker e.K.',
	'Pfannen Harecker',
	'Nägele Bedachungstechnik GmbH',
	'Nägele GmbH',
	'Merz Import Export',
	'Inh. Siegfried Merz e.K.',
	'Merz Import Export Inh. Siegfried Merz e.K.',
	'L. Müller GmbH',
	'Medizinisch-Technischer Gerätebau',
	'rückenfreundliche Möbel',
	'L. Müller GmbH',
	'Kottmair GmbH Garagentorbau',
	'Kottmair GmbH',
	'Hoch exclusiv',
	'Hoch exclusiv',
	'Deisl Sauna & Wellness',
	'Deisl Josef GmbH',
	'Deisl Sauna & Wellness',
	'beam GmbH',
	'beam GmbH',
	'Runggaldier Alfons',
	'Bildhauer',
	'Runggaldier',
	'Illerplastic Fensterbau GmbH',
	'Illerplastic Fensterbau',
	'Gürtler Bauelemente GmbH',
	'Gürtler & Dollinger',
	'Gürtler Bauelemente GmbH Gürtler & Dollinger',
	'E. Zimmermann GmbH',
	'E. Zimmermann GmbH',
	'Brigitte Salmanzadeh',
	'Inh. H. Salmanzadeh',
	'Brigitte Salmanzadeh',
	'JORDAN-Teppiche',
	'handgewebt',
	'JORDAN-Teppiche',
	'Favorit-Reinigungsgeräte',
	'Thomas Plura',
	'Favorit-Reinigungsgeräte',
	'Ing. Hermann Payer',
	'BIND-FIX PROFESSIONAL ELASTICS',
	'Ing. Hermann Payer',
	'Fliesen Auer GmbH',
	'Fliesen Auer',
	'Glonntaler Kachelofenbau GmbH',
	'Glonntaler Kachelofenbau',
	'Hilde Purzer',
	'Krippenfiguren Restaurationen',
	'Hilde Purzer',
	'Handels- u. Messevertrieb',
	'Tetzlaff',
	'Tetzlaff',
	'Tepek e.K. - Vollkunststoffprodukte',
	'Tepek e.K.',
	'Flötzer Klaus',
	'Inter. Messevertrieb der',
	'Schwarzwaldstände',
	'Flötzer Klaus',
	'VEINAL',
	'Schuster GmbH',
	'VEINAL',
	'Sascha Hönninger',
	'Insektenschutz - Sonnenschutz - Rollladen',
	'Sascha Hönninger',
	'Maria Buytaert',
	'Kerzen-Vertriebs GmbH',
	'Maria Buytaert',
	'Haas Fertigbau GmbH',
	'Haas Fertigbau GmbH',
	'VACUTOP',
	'VACUTOP',
	'Metallbau Rockermeier GmbH',
	'Metallbau Rockermeier',
	'ROLF BENZ PolsterHaus Schlosser',
	'Einrichtungs GmbH & Co. KG',
	'ROLF BENZ PolsterHaus Schlosser Einrichtungs GmbH & Co. KG',
	'Kliegl Treppenbau GmbH',
	'Kliegl Treppenbau',
	'B&L Elektrogeräte GmbH',
	'B&L Elektrogeräte',
	'SAWESA',
	'Sattlberger M. GmbH',
	'SAWESA Sattlberger M. GmbH',
	'Skiba Fensterabdichtungen',
	'Inh. Susanne Brosch',
	'Skiba',
	'Geba GmbH - Teppichgalerie',
	'Geba GmbH',
	'Möbelcenter biller GmbH',
	'Möbelcenter biller',
	'Kamintechnik König',
	'Kamintechnik König',
	'Lanakur Möbelhandels GmbH',
	'Lanakur',
	'DANBER ITALIA-',
	'CARLO E PIERA RATTI',
	'del Dr. Carlo Berruti  S.A.S.',
	'DANBER ITALIA',
	'Allwetterdach ESCO GmbH',
	'ESCO',
	'Laurastar Deutschland GmbH',
	'Laurastar',
	'Isartaler Holzhaus',
	'GmbH & Co. KG',
	'Isartaler Holzhaus',
	'Meisel & Gerken GmbH',
	'Meisel & Gerken',
	'Münchener Zeitungs-Verlag GmbH & Co. KG',
	'Münchner Merkur / tz',
	'Chiemgauer Weberei',
	'Teppiche nach Maß',
	'Chiemgauer Weberei',
	'Lampen Barabas',
	'Lampen Barabas',
	'Gartenmöbel Baumgartner',
	'Gartenmöbel Baumgartner',
	'Falto-Sanaform',
	'Falto-Sanaform',
	'BEIJ  International',
	'BEIJ  International',
	'WABECO',
	'Walter Blombach GmbH',
	'WABECO',
	'Schillinger Goldschmiedekunst',
	'Schillinger Goldschmiedekunst',
	'Schwanheimer Industriekleber GmbH',
	'Schwanheimer Industriekleber',
	'Marschollek GmbH',
	'Marschollek',
	'Ideal-Guss',
	'Ideal-Guss',
	'JOSKO',
	'Fenster und Türen GmbH',
	'JOSKO',
	'Peter Moser rustic-wood-tyrol',
	'Rustikale Holzbearbeitung Ges.m.b.H.',
	'rustic-wood-tyrol',
	'Karl-Heinz Häussler GmbH',
	'Karl-Heinz Häussler',
	'Simssee-Handweberei',
	'Teppiche nach Maß',
	'Simssee-Handweberei',
	'Erndl Küchen GmbH',
	'Erndl Küchen',
	'Zielinsky',
	'Universal-Stein GmbH & Co. KG',
	'Zielinsky',
	'Whirlpool Import GmbH',
	'Hot Spring Portable Spas',
	'Whirlpool Import GmbH',
	'Kolbe GmbH, Alfred',
	'Weihnachtskrippenfabrik',
	'Kolbe GmbH',
	'Kaindl-woodcarver ',
	'RKE Technik GmbH',
	'Kaindl-woodcarver',
	'Walter Moosburger KG',
	'Rosshaar-Manufactur',
	'Walter Moosburger KG Rosshaar-Manufactur',
	'Holz Schiller GmbH',
	'Holz Schiller GmbH',
	'Hark GmbH & Co. KG',
	'Kamin- und Kachelofenbau',
	'Hark GmbH & Co. KG',
	'Wolf System GmbH',
	'Wolf System',
	'Deutscher Bundestag',
	'Referat Öffentlichkeitsarbeit',
	'Deutscher Bundestag',
	'GIRA Giersiepen GmbH & Co. KG',
	'GIRA Giersiepen',
	'Norbert Woll  GmbH',
	'Norbert Woll  GmbH',
	'Vorwerk Deutschland Stiftung & Co. KG',
	'Geschäftsbereich Kobold',
	'Vorwerk',
	'Sozialverband VdK Bayern e.V.',
	'Sozialverband VdK Bayern e.V.',
	'Richard Czarny',
	'SecondLife',
	'Polsterungen & Restaurierungen',
	'Richard Czarny',
	'PRADO',
	'PRADO',
	'OBENLAND GmbH',
	'Reinigungsmittelhersteller',
	'OBENLAND GmbH',
	'Möbel Grollmus GmbH & Co. KG',
	'Möbel Grollmus',
	'Marohl Wintergarten GmbH',
	'Marohl Wintergarten GmbH',
	'Antiquitäten Rolf Klaeber',
	'Antiquitäten Klaeber',
	'Otto Bals',
	'Schreinerei',
	'Otto Bals Schreinerei',
	'Antiquitäten',
	'H. Durst',
	'Antiquitäten H. Durst',
	'Eckardt Albrecht',
	'Antike Bauernmöbel',
	'Eckardt Albrecht',
	'Vaillant Deutschland GmbH & Co. KG',
	'Vaillant Deutschland GmbH & Co. KG',
	'Wagenblast + Altmann GmbH',
	'Wagenblast + Altmann GmbH',
	'Siedra-Leitern GmbH',
	'Siedra-Leitern',
	'Kaindl Schleiftechnik - Reiling GmbH',
	'Kaindl Schleiftechnik',
	'CRANPOOL',
	'Grabner GmbH',
	'CRANPOOL',
	'Eckstein-Wasserenthärter GmbH',
	'Eckstein-Wasserenthärter',
	'Erich Adam',
	'Warenhandelsgesellschaft mbH',
	'EAW',
	'Juchem GmbH',
	'Juwelen-Atelier',
	'Juchem GmbH',
	'INNTAL-HANDWEBEREI',
	'Werner Rechenauer',
	'INNTAL-HANDWEBEREI',
	'GOLDBAUR',
	'Wolfgang Baur GmbH',
	'GOLDBAUR',
	'Raimund Josef Holzner',
	'Holzner Promotion',
	'Holzner Promotion',
	'Dachbeschichtung - Bauko',
	'Robert Demmelmair',
	'Dachbeschichtung - Bauko',
	'SML GmbH',
	'SML GmbH',
	'Robert Thomas Metall- und',
	'Elektrowerke GmbH & Co. KG',
	'Robert Thomas',
	'Ernst Schachner Ges.m.b.H.',
	'Wintergarten und Modulhaus',
	'Ernst Schachner Ges.m.b.H.',
	'RUKU Sauna Manufaktur',
	'GmbH & Co. KG',
	'RUKU Sauna Manufaktur',
	'Ralf Heine Alarmanlagen',
	'Ralf Heine Alarmanlagen',
	'Rundum Meir GmbH',
	'Rundum MeirGmbH',
	'LEAOS',
	'Des Armin Oberhollenzer',
	'LEAOS',
	'Spiess Manfred',
	"Manni's Meistertischlerei",
	'Spiess Manfred',
	'RIZZOLI s.r.l.',
	'RIZZOLI s.r.l.',
	'DEUR OHG',
	'DEUR',
	'EMBAWO',
	'EMBAWO',
	'Profilholz Passeier Genossenschaft',
	'Profilholz Passeier',
	'Zirbelzauber',
	'Inh. Diana Audi-Kalinka',
	'Zirbelzauber Inh. Diana Audi-Kalinka',
	'Larix OHG des Girardi Ernst & Co.',
	'Larix OHG',
	'Majoba',
	'Kunstkarten voll Lebenslust',
	'Majoba',
	'Orthopant Filzpantoffel GmbH',
	'Orthopant',
	'Bodo Demelius',
	'Bodo Demelius',
	'Musik Georg Plaschke',
	'Musik Georg Plaschke',
	'Tiroler Goldschmied GmbH',
	'Tiroler Goldschmied',
	'Galerie Hierl',
	'Galerie Hierl',
	'Casada Deutschland GmbH',
	'Casada',
	'Telekom Shop im Nassauer Haus',
	'EuroCom City GmbH & Co. KG',
	'Telekom Messeteam',
	'egger technologie GmbH',
	'egger technologie GmbH',
	'Bella Marmor',
	'Raymond Gutjahr',
	'Bella Marmor',
	'OBI GmbH & Co. Deutschland KG',
	'OBI GmbH',
	'AMR Wohn & Energiesparer GmbH',
	'AMR GmbH',
	'Manfred Deisl GmbH',
	'Deisl Parkettmanufaktur',
	'Manfred Deisl GmbH',
	'SAGEDER Fenster- und Türenwerk GmbH',
	'SAGEDER Fenster- und Türenwerk GmbH',
	'Aventi HANDELS GmbH',
	'Aventi HANDELS',
	'Zimmerei Gebrüder Dufter GmbH',
	'Zimmerei Dufter',
	'Santek GmbH',
	'Santek GmbH',
	'Grandl Sauna- und Innenausbau GmbH',
	'Grandl',
	'Sp. Rapido GmbH',
	'Sp. Rapido',
	'Helmut Walz',
	'Helmut Walz',
	'WIPPRO Türen Treppen Vertriebs GmbH',
	'WIPPRO',
	'ESW-Wohndesign',
	'ESW-Wohndesign',
	'BAVARIA',
	'Wohn- und Zweckbau GmbH',
	'BAVARIA Wohn- und Zweckbau GmbH',
	'Thomas Poganitsch',
	'Thomas Poganitsch',
	'Giotti Ceramiche',
	'di Biagiotti Mario & C. s.a.s.',
	'Giotti Ceramiche',
	'Paradies-Grills®',
	'Paradies-Grills®',
	'Sundarbans',
	'Lederwaren & Accessoires',
	'Sundarbans',
	'Primusmöbel AG',
	'Primusmöbel',
	'Unikatschmuck Regina Beck',
	'Regina Beck',
	'Goldspindel',
	'Christiane Bekk',
	'Christiane Bekk',
	'HAMMER STORES GmbH',
	'FITNESSGERÄTE FÜR ZU HAUSE',
	'HAMMER Stores',
	'Taylor Ahauser Gefahrensysteme',
	'Taylor Ahauser',
	'Sangalli Sonia',
	'Sangalli Sonia',
	'Betten Klobeck',
	'Betten Klobeck',
	'Heller-Vertrieb',
	'Inh. Norbert Heller',
	'Heller-Vertrieb',
	'ferobau',
	'Franz X. Steigenberger',
	'ferobau',
	'Meier Balkone',
	'Meier Balkone',
	'Claudia Liesegang',
	'Schmuck',
	'Claudia Liesegang',
	'Modemanufaktur Diverso',
	'Diverso',
	'ErgoVitalis GmbH',
	'ErgoVitalis',
	'Olbrish Produkt GmbH',
	'Olbrish',
	'NEFF First-Choice-Diamonds',
	'NEFF',
	'Dhouib Olivenholz',
	'Dhouib Olivenholz',
	'Memo Garden by MEMO STEEL GmbH',
	'Memo Garden by MEMO STEEL GmbH',
	'Fellhandlung U-TEX',
	'U-TEX',
	'Insekt Direkt UG',
	'Insekt Direkt',
	'Fensterhaus München GmbH',
	'Fensterhaus München',
	'Just Grace',
	'Just Grace',
	'Holzweg-Mareis - Onlineversand von woody Holzschuhen & Accessoires',
	'Holzweg-Mareis',
	'Galerie Munk',
	'Galerie Munk',
	'Niedermayr Virgil GmbH',
	'Wintergartenbau',
	'Niedermayr Virgil GmbH Wintergartenbau',
	'Müller & Sattler Uhrenbausatz GmbH',
	'by Erwin Sattler',
	'Müller & Sattler',
	'Glasbläsermeister S. Firley',
	'Rahmenspezialist',
	'Glasbläsermeister Firley Rahmenspezialist',
	'Viet Nam Silk Pte',
	'Thi My Dung Tran',
	'Viet Nam Silk',
	'HWG Products GmbH',
	'HWG Products',
	'Andamooka Opal',
	'Rosina Förster',
	'Andamooka',
	'Jh Elektronik',
	'Fachbetrieb für Alarmanlagen',
	'Inh. Jürgen Hummel',
	'Jh Elektronik',
	'Miele-Studio',
	'Knauseder GmbH',
	'Miele-Studio',
	'Willi Weber & Sohn GmbH',
	'Diamantenschleiferei',
	'Juwelenfabrikation',
	'Willi Weber & Sohn',
	'Schreinerei Peter Knöpfle',
	'Schreinerei Peter Knöpfle',
	'Mirza arts and crafts',
	'Mirza arts and crafts',
	'Mauro Poiatti',
	'Mauro Poiatti',
	'illycaffè S.p.A.',
	'Niederlassung Deutschland',
	'illycaffè S.p.A.',
	'Alpha-Fenstersysteme',
	'Alpha-Fenstersysteme',
	'123infrarot.eu',
	'Inh. Hans-Jürgen Volz',
	'123infrarot.eu',
	'divo-electronics',
	'divo-electronics',
	'Compass Pools Deutschland GmbH',
	'Compass Pools',
	'Reps GmbH',
	'Schwimmbad Whirlpool Haustechnik',
	'Reps GmbH',
	'Sitzmarkt.de',
	'Sitzmarkt.de',
	'Kollux GmbH',
	'Kollux',
	'hapa AG',
	'Kunststofffenster- und Rollladenwerke',
	'hapa AG',
	'Martin Knop Wannenaustausch',
	'Martin Knop Wannenaustausch',
	'Zimmerei Winter GmbH & Co. KG',
	'Zimmerei Winter',
	'Alpha Techno GmbH',
	'Alpha Techno',
	'Höffner Möbelgesellschaft GmbH & Co. KG',
	'Höffner Möbelgesellschaft GmbH & Co. KG',
	'Küchenexpert GmbH',
	'Küchenexpert',
	'Riedinger Massivholz-Möbel GmbH',
	'Riedinger',
	'EVO Vertrieb Deutschland GmbH',
	'EVO Vertrieb Deutschland GmbH',
	'GRUBER - SAUNA',
	'RM Wellness GmbH',
	'GRUBER',
	'KBK UNERTL GmbH',
	'Fenster u. Wintergarten',
	'FINSTRAL Profi-Partner',
	'KBK Unertl GmbH Fenster u. Wintergarten',
	'Haböck & Weinzierl GmbH',
	'Haböck & Weinzierl',
	'MAX',
	'di Paoletti Massimiliano',
	'MAX',
	'Luise Accessoires',
	'Luise Accessoires',
	'Wintergarten Gruber GmbH & Co. KG',
	'Wintergarten Gruber GmbH & Co. KG',
	'Alutechnik Matauschek GmbH',
	'Alutechnik Matauschek',
	'Worbis',
	'Worbis',
	'OPTIMA Schlafsysteme',
	'Schubert GmbH',
	'OPTIMA',
	'LBS GD München',
	'LBS GD München',
	'Ramona Leiß',
	'Ramona Leiß',
	'G.F.C.',
	'G.F.C.',
	'Goldschmiede Fanny Bollig',
	'Fanny Bollig',
	'Buchberger GmbH',
	'Badstudio',
	'Sanitär- und Heizungstechnik',
	'Buchberger GmbH',
	'Ofenwelt GmbH',
	'* Die ganze Welt der Öfen! *',
	'Kachelöfen * Grundöfen * Heizkamine * Kaminöfen',
	'OFEN WELT',
	'Step Forward GmbH',
	'Step Forward',
	'Fischer Werksvertretungen',
	'Carport Werksvertretung Süd',
	'Fischer Werksvertretungen',
	'remos Professional Body Care',
	'Reinhard Mössmer e.U.',
	'remos Scheren, Pinzetten',
	'FAWAS GmbH',
	'SAUBERE GESUNDE LEBENSRÄUME',
	'FAWAS GmbH',
	'Sascha Böhmer GmbH & Co. KG',
	'Sascha Böhmer GmbH',
	'Dynaglobe Products GmbH & Co. KG',
	'Dynaglobe Products',
	'ELRAS',
	'Regina Klopp',
	'ELRAS',
	'Hafner Kachelofenbau',
	'Inhaber: Johann Hafner',
	'Hafner Kachelofenbau',
	'Der Schuhbutler',
	'Der Schuhbutler',
	'Lonni e Mantova di',
	'Gian Luigi Lonni e Giampietro Mantova snc',
	'Lonni e Mantova',
	'Helvetic GmbH',
	'Helvetic GmbH',
	'Monika Stöckinger',
	'Monika Stöckinger',
	'Brendel Bauelemente Wintergarten',
	'Brendel Bauelemente Wintergarten',
	'Zirbenherz GmbH',
	'Zirbenherz',
	'Pulgar Import Export S. A.',
	'Pulgar S. A.',
	'ART of SYLVA - Kunst & Design',
	'Sylvia Haigermoser',
	'www.art-of-sylva.de',
	'ART-of-SYLVA',
	'Kunstwerkstatt Stange GmbH',
	'Kunstwerkstatt Stange',
	'Barbaras Kreative Welt',
	'Barbaras Kreative Welt',
	'Die Welt der 1.000 Klänge',
	'Inh. Florian Raeck',
	'Die Welt der 1.000 Klänge',
	'Alpen Relax by Ruwies',
	'Inhaber: Wieser Rudolf',
	'Alpen Relax',
	'Die Outdoorküche',
	'Die Outdoorküche',
	'Franz Szeredy GmbH',
	'Küchendesign Szeredy',
	'Franz Szeredy',
	'Systembau Bruckert GmbH & Co. KG',
	'Systembau Bruckert',
	'Steimer! Innovative Heizsysteme',
	'Steimer!',
	'De´Longhi Deutschland GmbH',
	'Geschäftsbereich Kenwood',
	'De´Longhi Deutschland',
	'W. Wiltschka',
	'W. Wiltschka',
	'Maria Haider',
	'COSMETIC',
	'Maria Haider',
	'Chiemgauer Kachelöfen',
	'Kachel und Keramik GmbH',
	'Chiemgauer Kachelöfen',
	'MyTherm Systems GmbH',
	'MyTherm Systems',
	'Paperpearl',
	'Paperpearl',
	'CEWE Stiftung & Co. KGaA',
	'CEWE',
	'Kunst & Garten GmbH',
	'-Gartengestaltung-',
	'Kunst & Garten',
	'Lirutti-Holzkultur',
	'Lirutti-Holzkultur',
	'NB KONTOR GmbH',
	'NB KONTOR',
	'Leonie Lackmann-Wisskirchen GmbH',
	'Leonie Lackmann-Wisskirchen',
	'Glamour',
	'leather & accessoires',
	'Glamour',
	'Kaminkehrer-Innung',
	'Oberbayern',
	'Kaminkehrer-Innung',
	'Biffar GmbH & Co. KG',
	'Niederlassung München',
	'Biffar GmbH & Co. KG',
	'Siegfried Muxel',
	'Siegfried Muxel',
	'Service für Sicherheitstechnik',
	'Service für Sicherheitstechnik',
	'Siegbert Negele',
	'Function Wall',
	'Siegbert Negele',
	'CLIPBOART GmbH',
	'CLIPBOART GmbH',
	'Beauty Line Technology Kft.',
	'Beauty Line Technology',
	'Hain Industrieprodukte Vertriebs-GmbH',
	'Hain Natur-Böden',
	'Stühlchen&Co.',
	'Stühlchen&Co.',
	'planHAUS',
	'Heim+Handwerk',
	'planHAUS',
	'Kaschmir & mehr',
	'Kaschmir & mehr',
	'Bau-Fuchs GmbH',
	'Bau-Fuchs',
	'AFG Reinigungssysteme',
	'Mack & Radzuweit Handels GmbH',
	'AFG Reinigungssysteme',
	'Holzbau B. Winkler GmbH',
	'Holzbau B. Winkler',
	'Edelstahlbild Sabine Kottmayr',
	'Edelstahlbild Sabine Kottmayr',
	'PALAIS DES MIRINIDES',
	'PALAIS DES MIRINIDES',
	'Massiv-Holz-Mauer',
	'Entwicklungs GmbH',
	'Massiv-Holz-Mauer Entwicklungs GmbH',
	'EFG Energie für Gebäude KG',
	'EFG KG',
	'BAYERNenergie e.V. Unabhängige Energieberater',
	'BAYERNenergie',
	'Stiehle',
	'Küche & Bad Naturenergie',
	'Stiehle',
	'Schreinerei Georg Holzner',
	'Schreinerei Georg Holzner',
	'Schreinerei Risch',
	'Schreinerei Risch',
	'Schreinerei Bachhuber,',
	'Inhaber Wolfgang Hinz',
	'Schreinerei Bachhuber, Inhaber Wolfgang Hinz',
	'werkhaus GmbH & Co.KG',
	'werkhaus GmbH',
	'Schreinerei Heumeier e.K.',
	'Schreinerei Heumeier e.K.',
	'Schreinerei Kirschner',
	'Schreinerei Kirschner',
	'Thoma Innenausbau GbR',
	'Thoma Innenausbau',
	'Schreinerei Loferer GmbH',
	'Schreinerei Loferer GmbH',
	'Schreinerei Werner Plaschke',
	'Möbelwerkstätten GmbH',
	'Schreinerei Werner Plaschke',
	'Vakuumiersysteme',
	'Handelsagentur Martina Johannes',
	'Martina Johannes',
	'TBA Hausgeräte',
	'Inh. Thomas Bald',
	'TBA Hausgeräte',
	'Huber Holzbau GmbH',
	'Huber Holzbau GmbH',
	'Kasbah Art Tresor',
	'Kasbah',
	'FenDesign Fenster und Türen GmbH',
	'FenDesign Fenster und Türen GmbH',
	'STROKA David Stroka',
	'STROKA',
	'Jörg GmbH',
	'Bauunternehmen - Bautenschutz',
	'Jörg GmbH',
	'WanDeco Wandverkleidungen',
	'Fa. Manfred Hörl e.K.',
	'WanDeco',
	'Möbel Willinger GmbH',
	'exklusiv mit brühl',
	'Möbel Willinger',
	'Kuffer Fenster- und Türentechnik KG',
	'Kuffer Fenster- und Türentechnik',
	'WEMA Flüssigtapete e.K.',
	'WEMA',
	'Physiotherm GmbH Deutschland',
	'Physiotherm GmbH Deutschland',
	'IRM Handloom & Handicrafts',
	'IRM',
	'Artinar Tunesia',
	'Artinar Tunesia',
	'Nazir Ahmad Mir',
	'Nazir Ahmad Mir',
	'BB-Sanierung',
	'BB-Sanierung',
	'Elegant',
	'Elegant',
	'Bruno Biancolino',
	'Bruno Biancolino',
	'FRA.FE.GIU DI FRANZESE',
	'FERNANDO GIULIO',
	'FRA.FE.GIU DI FRANZESE',
	'Biancolino Raffaele',
	'Maremy Italy',
	'Biancolino',
	'Electrolyte GmbH',
	'Electrolyte',
	'Krauhan OG',
	'Krauhan',
	'Style & Déco',
	'La Villa',
	'Style & Déco',
	'BETTENRID GmbH',
	'BETTENRID GmbH',
	'Robert Bauer',
	'Fresh Juice',
	'Fresh Juice',
	'Sports & Spirit',
	'Sports & Spirit',
	'SelfStorage Dein Lagerraum GmbH',
	'SelfStorage GmbH',
	'POS lifestyle GmbH',
	'POS lifestyle',
	'Bauzentrum',
	'der Landeshauptstadt München',
	'Bauzentrum München',
	'LT Weigel GmbH',
	'Lamellenüberdachungstechnik',
	'LT Weigel GmbH',
	'Torsten Behrendt',
	'Messen und Märkte',
	'Behrendt',
	'THE KNOTS UG',
	'THE KNOTS',
	'lukkizzi',
	'lukkizzi',
	'bartmann berlin GbR',
	'bartmann berlin',
	'Bullenberg UG',
	'Bullenberg',
	'stocubo GmbH',
	'stocubo',
	'Sitzfeldt GmbH',
	'Sitzfeldt GmbH',
	'Moltke',
	'Wintergärten und Baudienstleistungen',
	'Moltke Wintergärten und Baudienstleistungen',
	'Caresse Holzmanufaktur GmbH',
	'Caresse Holzmanufaktur',
	'LiftTec GmbH',
	'LiftTec',
	'Paul & Christian Harlander GbR',
	'Harlander GbR',
	'Schreinerei Ziegelmeier GmbH & CO KG',
	'Schreinerei Ziegelmeier',
	'Schreinerservice Bayern GmbH',
	'Schreiner Bayern',
	'Pode',
	'Pode',
	'dieschmidt –',
	'Fachverlag für gedruckte und digitale Medien e.K.',
	'dieschmidt',
	'Nectar Arts & Handicrafts',
	'Nectar',
	'Lohberger Heiztechnik GmH',
	'Lohberger Heiztechnik',
	'Nzusyo Mutisya',
	'Nzusyo Mutisya',
	'ATELIER E.S.',
	'ATELIER E.S.',
	'Victor Zavaleta',
	'Mineralien aus Peru',
	'Mineralien aus Peru',
	'Armando Onate',
	'Armando Onate',
	'Zenko, Solvis - Handelsvertretung',
	'Zenko, Solvis',
	'Cosy Home Ideas',
	'by Signature Home Collection GmbH',
	'Cosy Home Ideas',
	'Superior Art & Handicrafts',
	'Superior Arts',
	'Eichinger Schreinerei GmbH',
	'Wintergartenbau',
	'Eichinger Schreinerei GmbH Wintergartenbau',
	'Bezirk Oberbayern -',
	'Oberbayerischer Förderpreis für Angewandte Kunst',
	'Bezirk Oberbayern',
	'Seidel Schmuck',
	'Seidel Schmuck',
	'Gardella Establishment',
	'Gardella Establishment',
	'FashionFab',
	'FashionFab',
	'M+W Design',
	'Gabriele Witte',
	'M+W Design',
	'Bundesverband Deutsches Zinngießerhandwerk e.V.',
	'Deutsches Zinngießerhandwerk',
	'MKA Enterprise',
	'MKA Enterprise',
	'Geldhauser ',
	'Die Münchner Busreisen',
	'Geldhauser Die Münchner Busreisen',
	'de´qua jürgen gebauer',
	'de´qua',
	'Klaus Schuler',
	'Lederwarenvertrieb',
	'Klaus Schuler',
	'Maxi-Marionetten',
	'Maximiliane Kiermeier',
	'Maxi-Marionetten',
	'Erich Niemeier',
	'Erich Niemeier',
	'Wollzeit GmbH',
	'Wolldecken & Plaids ...natürlich aus Wolle',
	'Wollzeit',
	'X-Mas Art Hartmann Handels GmbH',
	'Hartmann Handels GmbH',
	'X-Mas Art',
	'Brazil Lederwaren GmbH',
	'Brazil Lederwaren',
	'Taschen Design Gabriele Drescher',
	'Gabriele Drescher',
	'Mariposa GmbH',
	'Mariposa GmbH',
	'OPAL Direkt',
	'Martin Tumann E.K.',
	'OPAL Direkt',
	'Heuer Schmuck',
	'Heuer Schmuck',
	'Hermann Veeh GmbH & Co.KG',
	'Veeh-Harfe',
	'Edler Holzschmuck',
	'Edler Holzschmuck',
	'Gröbner Landhausmöbel',
	'Gröbner',
	'[hantwerck]',
	'[hantwerck]',
	'Schmuckstücke Bettina Kieffer',
	'Bettina Kieffer',
	'COCO-MAT SA MATTRESS PRODUCTION',
	'COCO-MAT SA',
	'Imotex GmbH',
	'Imotex',
	'Alpenkorb-Manufaktur GmbH',
	'Alpenkorb-Manufaktur',
	'Rieser Aufzugbau GmbH',
	'Rieser Aufzugbau',
	'Reviermanufaktur GmbH',
	'Reviermanufaktur',
	'Int.-trade',
	'Ahmed Shamim',
	'Int.-trade',
	'Dörfler GmbH',
	': Fenster : Türen : Parkett :',
	'Dörfler GmbH',
	'LeStoff e.U.',
	'LeStoff e.U.',
	'Keramik-Atelier Handke',
	'Inh. Melissa Handke',
	'Keramik-Atelier Handke',
	'Anton Schöb',
	'Fenster- u. Treppenbau',
	'GmbH & Co. KG',
	'Anton Schöb Fenster- u. Treppenbau',
	'Thermofit AG',
	'Thermofit',
	'Modedesign Marion Terhart',
	'Modedesign Marion Terhart',
	'Lehner Renovierungsfachbetrieb GmbH',
	'Lehner',
	'ZAUNZAR Bayern',
	'ZAUNZAR Bayern',
	'SOWE Sonnen & Wetterschutztechnik',
	'SOWE Sonnen & Wetterschutztechnik',
	'MarmorPower GmbH',
	'MarmorPower',
	'GOLDSTEIN Créations SAS',
	'GOLDSTEIN Créations',
	'Josef Heckmeier Haustechnik GmbH',
	'Josef Heckmeier Haustechnik GmbH',
	'FW-Glas GmbH',
	'FW-Glas',
	'Südklang Harmonika',
	'Vertrieb Jernej Brilej',
	'Südklang Harmonika',
	'DOLFI - AMC SRL',
	'DOLFI - AMC',
	'Gasser Naturstein',
	'des Gasser Thomas & Co. K',
	'Gasser Naturstein',
	'Schreinerei Würzburger GmbH',
	'Schreinerei Würzburger GmbH',
	'Inter-Pietre Sparber GmbH',
	'Inter-Pietre Sparber',
	'Zacher Johann & Co.OHG',
	'Zacher',
	'Schreinerei Finauer',
	'Schreinerei Finauer',
	'Puschtra Company KG',
	'Puschtra Company',
	'Daheim Liefer-Service GmbH',
	'Lesezirkel LESERKREIS DAHEIM',
	'Leserkreis Daheim',
	'KnezHolz GmbH',
	'KnezHolz',
	'Magri & M. s.r.l.',
	'Magri & M.',
	'Tasci Hamit',
	'Tasci Hamit',
	'Karl Sturm',
	'Gondolo Wiegeliegen',
	'Karl Sturm',
	'Treppenrenovierungssysteme',
	'Stephan Bierwirth',
	'Stephan Bierwirth',
	'Müller',
	'Müller',
	'buy to help',
	'gemeinnützige UG (haftungsbeschränkt)',
	'buy to help',
	'WENATEX',
	'WENATEX',
	'VOIT Schreinerei und Planung GmbH',
	'VOIT GmbH',
	'Turbilineclean S.r.l.',
	'Turbilineclean',
	'Fachverband Matratzen-Industrie e.V.',
	'Matratzen-Industrie e.V.',
	'form.bar by okinlab (Okinlab GmbH)',
	'form.bar by okinlab',
	'the curtain.shop',
	'the curtain shop',
	'bloomon',
	'bloomon',
	'COCO-MAT Muenchen',
	'COCO-MAT Muenchen',
	'Houzz Germany GmbH',
	'Houzz Germany',
	'Wohntheater',
	'powered by Houzz',
	'Wohntheater',
	'Almer Tischlerei GmbH',
	'Almer Tischlerei',
	'HPCSALT.DESIGN',
	'HPCSALT.DESIGN',
	'Carbon4 Heizsysteme GmbH',
	'Carbon4 Heizsysteme',
	'Bäumler GmbH & Co.',
	'Bäumler',
	'Brumberg Leuchten GmbH & Co. KG',
	'Brumberg Leuchten',
	'STUDIO 49',
	'Musikinstrumentenbau GmbH',
	'STUDIO 49',
	'Rall Guitars & Tools',
	'Rall Guitars & Tools',
	'Striebel Gitarrenbau',
	'Striebel',
	'Orgelbau Franz Schreier',
	'Orgelbau Franz Schreier',
	'Munich Guitar Company',
	'Kozlik + Zirnbauer GbR',
	'Munich Guitar Company Kozlik + Zirnbauer GbR',
	'Schreinerei & Beleuchtung',
	'Benedikt Adolff',
	'Licht im werkhaus',
	'Karl Höfner GmbH & Co. KG',
	'Karl Höfner',
	'Staudenschreiner Holzbau GmbH',
	'Staudenschreiner Holzbau',
	'Conviva design',
	'Conviva design',
	'Bayerland Harmonika Akkordeon',
	'Konrad Rahm',
	'Harmonika Akkordeon',
	'Pianohaus',
	'Carl Hirsch',
	'Carl Hirsch',
	'Big Sleep GmbH',
	'Wasserbetten- und',
	'Möbelvertriebs-',
	'Big Sleep GmbH',
	'EcoVie',
	'Fashion',
	'EcoVie Fashion',
	'Claudias Taschenladen',
	'Claudias Taschenladen',
	'Hot Design Innovation s.r.l.s',
	'Lorenzo Corneli',
	'Hot Design Innovation',
	'Door 360 Schiebetüren & Raumteiler- Max Weidlich',
	'Door 360',
	'Christoph Fischer GmbH',
	'EM-Chiemgau',
	'Christoph Fischer',
	'Jain enterprises',
	'Jain enterprises',
	'EGC Elisabeth von der Groeben Collection',
	'EGC',
	'Oops LS',
	'Oops LS',
	'KristallSalzWelt',
	'SalzManufaktur',
	'Salzkammergut',
	'KristallSalzWelt',
	'NEPARU HANDICRAFT TRADING',
	'NEPARU',
	'LandIDEE Verlag GmbH',
	'LandIDEE Verlag',
	'Rüegg Studio Oberbayern',
	'Rüegg Studio',
	'3Möbel+',
	'3Möbel+',
	'Vereinigte Riederinger Hafnerei GmbH',
	'Riederinger Hafnerei',
	'Himal International',
	'Himal International',
	'Kohlbeck Keramik e.K.',
	'Kohlbeck Keramik',
	'Kettler & Mabi Bügelsysteme',
	'Mabi GmbH Bierekofen',
	'Kettler & Mabi',
	'Kings Hand Germany GmbH',
	'Kings Hand Germany',
	'KüchenTRENDS',
	'Heim+Handwerk',
	'KüchenTRENDS',
	'Münchner Bank eG',
	'Münchner Bank eG',
	'rennerdesign',
	'rennerdesign',
	'OPIUM OUTLET',
	'OPIUM OUTLET',
	'Der Holzladen',
	'Der Holzladen',
	'Reinartz Babyland',
	'Reinartz Babyland GmbH',
	'HAUS-TROCKEN.COM - MORITZ KG',
	'HAUS-TROCKEN.COM',
	'Holzdruck Malte Dinkela',
	'Holzdruck Malte Dinkela',
	'Exquisit Parkett und Gestaltung',
	'Werner Etzig',
	'Exquisit Parkett und Gestaltung',
	'Josef Bergmann',
	'Haustechnik',
	'Josef Bergmann',
	'Manfred Beha',
	'Malerbetrieb Beha',
	'Malerbetrieb Beha',
	'Galerie Reichold',
	'Galerie Reichold',
	'Klarinetten-Manufaktur Dörfler, Geretsried',
	'Meisterwerkstatt für',
	'Holzblasinstrumente',
	'seit 1951',
	'Klarinetten-Manufaktur Dörfler, Geretsried',
	'Lovely Snow',
	'Lovely Snow',
	'Ing. Richard Štrych',
	'Ing. Richard Štrych',
	'Jallali Omar',
	'Jallali Omar',
	'Aimex Aicha import-export',
	'Aimex Aicha',
	'Artesania Las Peruanitas',
	'Artesania Las Peruanitas',
	'Leuma-Leutschacher-KG',
	'Leuma-Leutschacher',
	'Aluminium-Fensterläden Wennesheimer',
	'Wennesheimer',
	'Martin Asanger',
	'Martin Asanger',
	'Lou&Dejlig',
	'Lou&Dejlig',
	'das kleine b',
	'das kleine b',
	'woodmosphere GbR',
	'woodmosphere',
	'Hafenholz',
	'Bagdahn & Völkel GbR',
	'Hafenholz',
	'Franz Renaltner',
	'Fenster und Türen',
	'Franz Renaltner',
	'Klassik Radio AG',
	'Klassik Radio',
	'Jan Cray',
	'Möbel',
	'Jan Cray',
	'Demeter-Weingut im Zwölberich',
	'Weingut Demeter',
	'Galerie Unlimited',
	'Galerie Unlimited',
	'KRIST & MÜNCH GmbH & Co. KG',
	'KRIST & MÜNCH GmbH & Co. KG',
	'OPTIMA Musiksaiten GmbH',
	'OPTIMA Musiksaiten GmbH',
	'Marina Moda',
	'Marina Moda',
	'Kashmir Royal Touch',
	'Kashmir Royal Touch',
	'Teppichservice Naini',
	'Teppichservice Naini',
	'HOFART',
	'Einrichtungen',
	'HOFART Einrichtungen',
	'R & G GBR',
	'RAUM concept store',
	'R & G GBR RAUM concept store',
	'Stefanie Raum Contemporary Interior',
	'Stefanie Raum Contemporary Interior',
	'Maler und Lackierer-Innung München',
	'Stadt und Land',
	'Maler und Lackierer Innung München Stadt und Land',
	'Lignum Arts GmbH',
	'Lignum Arts GmbH',
	'RTL2 Fernsehen GmbH & Co. KG',
	'RTL2 Fernsehen GmbH & Co. KG',
	'fairbag',
	'fairbag',
	'Michael Jobst',
	'Michael Jobst',
	'Musik Hartwig',
	'Zupfinstrumentenbau',
	'Musik Hartwig Zupfinstrumentenbau',
	'Thomas Beckstein',
	'fett - handmade upcycling products',
	'Thomas Beckstein fett - handmade upcycling products',
	'Xuyan Wu',
	'Xuyan Wu',
	'Die Möbelmacher GmbH',
	'Möbelmacher',
	'Kunstwerkstätte David Wiemer',
	'Kunstwerkstätte David Wiemer',
	'Keyswerk Musikelektronik',
	'Boehm Orgeln',
	'SELEPACK ITALIA SRL',
	'Novotono',
	'SELEPACK ITALIA SRL Novotono',
	'HS HausStrom Management GmbH',
	'HausStrom GmbH',
	'Frankenlifte',
	'Frankenlifte',
	'Christ Baubeschichtungen',
	'Christ Baubeschichtungen',
	'LIMUNDO',
	'Kinderleuchten',
	'LIMUNDO',
	'Handelsagentur Sport und Lauf',
	'Handelsagentur Sport und Lauf',
	'Richard Kanta Skloart',
	'Richard Kanta Skloart',
	'WWS Haustechnik GmbH',
	'WWS Haustechnik GmbH',
	'NoDesign Planungs GmbH',
	'NoDesign Planungs GmbH',
	'Safe4u Alarmanlagen',
	'Safe4u',
	'Streich- und Zupfinstrumentenmacher-',
	'Innung Erlangen',
	'Streich- und Zupfinstrumentenmacher- Innung Erlangen',
	'Andreas Prüfer',
	'fern-holz',
	'Andreas Prüfer fern-holz',
	'Fluhr Displays e.K.',
	'drahtmanufaktur',
	'Fluhr Displays e.K. drahtmanufaktur',
	'Otto Weitzmann AG',
	'Otto Weitzmann AG',
	'ECOBEGLASS',
	'German Glaser',
	'ECOBEGLASS German Glaser',
	'Just Services GmbH',
	'Just Services GmbH',
	'Wartelsteiner GmbH',
	'Wartelsteiner GmbH',
	'John Dee Zimmermann',
	'John Dee Zimmermann',
	'Connecting Lights GmbH',
	'Sacrea Lichtkunst',
	'MOODMINT',
	'MOODMINT',
	'Jochum & Tomasevic GbR',
	'Jochum & Tomasevic GbR',
	'Sachverständiger Geiger',
	'Sachverständiger Geiger',
	'Antikes Ruffini',
	'Antikes Ruffini',
	'Slow Cotó',
	'Guillermo Varela Tacre',
	'Slow Cotó Guillermo Varela Tacre',
	'Haus der Bilder',
	'Lothar Baumeister',
	'Haus der Bilder',
	'Bambus-Living',
	'Bambus-Living',
	'Imperial Shawls',
	'Imperial Shawls',
	'H&Z Corporation Ltd',
	'H&Z Corporation Ltd',
	'Max Renaltner GmbH',
	'Max Renaltner GmbH',
	'Flor de Luna',
	'Flor de Luna',
	'FLORENCEBAGS IRELAND LTD',
	'FLORENCEBAGS IRELAND LTD',
	'Figli di De Martini Giuseppe Snc',
	'Figli di De Martini Giuseppe Snc',
	'Snow Leopard Projects GmbH',
	'Snow Leopard Projects GmbH',
	'PEC Professional',
	'Energy Consulting',
	'PEC Professional Energy Consulting',
	'Tikiwe',
	'Taschen aus Kork',
	'Tikiwe',
	'Kellinger',
	'Kellinger',
	'Ciro Marcos Aceto Lorenzoni',
	'Vera Navarro Goldene Grass',
	'Ciro Marcos Aceto Lorenzoni Vera Navarro Goldene Grass',
	'Madame Butterfly',
	'Madame Butterfly',
	'Müller Möbelwerkstätten GmbH',
	'Müller Möbelwerkstätten GmbH',
	'Thomas Böhmer',
	'Thomas Böhmer',
	'Connox GmbH',
	'Connox GmbH',
	'Bernhard Schmid',
	'Künstler - Holzgestalter',
	'Bernhard Schmid Künstler - Holzgestalter',
	'HOWE Warenhandels GmbH',
	'Möbel Outlet Zentrum',
	'HOWE Warenhandels GmbH Möbel Outlet Zentrum',
	'youlittle GmbH',
	'Oliver Frank',
	'youlittle GmbH Oliver Frank',
	'ReVital Duft & Genuss',
	'ReVital Duft & Genuss',
	'Volkskamine.de',
	'Volkskamine.de',
	'2 C-Möbel Berlin Cramer + Cramer GmbH',
	'2 C-Möbel Berlin Cramer + Cramer GmbH',
	'Hummel, Winkler, Löser GbR',
	'Hummel, Winkler, Löser GbR',
	'KBB Wand & Bodenbeläge',
	'KBB Wand & Bodenbeläge',
	'PRM GmbH',
	'PRM GmbH',
	'Hermes-Technik GmbH & Co. KG',
	'Hermes-Technik GmbH & Co. KG',
	'LEDERLAND WIESBADEN - W.S.D. GMBH',
	'LEDERLAND WIESBADEN',
	'Dariusz Gidelski',
	'FOLKROLL',
	'Dariusz Gidelski FOLKROLL',
	'DEUTSU GmbH',
	'DEUTSU',
	'Christine Kröncke Interior Design GmbH',
	'Christine Kröncke Interior Design GmbH',
	'DKey Trade e.U / DECOROUS',
	'DKey Trade e.U / DECOROUS',
	'Traumduft GmbH',
	'Traumduft GmbH',
	'KIS CONCEPT GmbH',
	'Coffee Airstream',
	'KIS CONCEPT GmbH',
	'Lulu Deco GmbH',
	'Lulu Deco GmbH',
	'bm symphonic GmbH',
	'bm symphonic GmbH',
	'Robert Worischek',
	'Metallblasinstrumentenbau',
	'Robert Worischek Metallblasinstrumentenbau',
	'ruja - GmbH',
	'Spezial - Reinigungs- und Pflegemittel',
	'ruja - GmbH Spezial - Reinigungs- und Pflegemittel',
	'PLAMECO Fachbetrieb Ziegler',
	'PLAMECO Fachbetrieb Ziegler',
	'Mangala-Group',
	'Thomas Schäfer',
	'Mangala-Group Thomas Schäfer',
	'Emporio Kashmir',
	'Emporio Kashmir',
	'Gebrüder Eggerz UG',
	'(haftungsbeschränkt) + Co.KG',
	'Gebrüder Eggerz UG (haftungsbeschränkt) + Co.KG'
]);
module.exports.getAnswer = word => {
	// create output Json structure
	var answer = fm.get(word);
	return answer;
};
